apiVersion: v1
kind: ConfigMap
metadata:
  name: webapp-config
  namespace: dev
data:
  ENVIRONMENT: DEV
  HOST: localhost
  PORT: "8000"
  REDIS_HOST: redis
  REDIS_PORT: "6379"
  REDIS_DB: "0"


---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapp
  namespace: dev
  labels:
    app: webapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapp
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: gcr.io/abdelrahman-377520/myappimg:3
        ports:
        - containerPort: 8000
        envFrom:
        - configMapRef:
            name: webapp-config


---
apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: dev
spec:
  type: LoadBalancer
  ports:
    - port: 8000
      targetPort: 8000
  selector:
    app: webapp