steps:
  # - name: 'gcr.io/cloud-builders/docker'
  #   id: Build
  #   args:
  #   - 'build'
  #   - '-t'
  #   - 'gcr.io/joes-project-379413/hello-cloudbuild'
  #   - '.'
  # - name: 'gcr.io/cloud-builders/docker'
  #   id: Push
  #   args:
  #   - 'push'
  #   - 'gcr.io/joes-project-379413/hello-cloudbuild'
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    dir: '.'
    args:
     - '-c'
     - |
       pwd
       ls
       #echo "$_MYVR"
       #python3 myf.py
       # echo "$_TEST"
       # echo "$PROJECT_ID"
    # env:  
    # - 'MYVR=$_MYVR'
options:
  logging: CLOUD_LOGGING_ONLY



# steps:
#   - name: gcr.io/cloud-builders/gcloud
#     args:
#       - '-c'
#       - >
#         gcloud auth list 


#         msg=$(gcloud pubsub subscriptions pull --auto-ack --format="value(data)"
#         my-topic-sub | base64 -d)

#         echo $msg 


#         var1=$(echo $msg | sed -n 's/.*"VAR1": "\(.*\)",.*/\1/p')

#         echo $var1
#     dir: .
#     entrypoint: bash
# options:
#   logging: CLOUD_LOGGING_ONLY

