steps:
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
    - 'build'
    - '-t'
    - 'us-central1-docker.pkg.dev/joes-project-379413/my-repo-cloudbuild/hello-cloudbuild'
    - '.'
  - name: 'gcr.io/cloud-builders/docker'
    id: Push
    args:
    - 'push'
    - 'us-central1-docker.pkg.dev/joes-project-379413/my-repo-cloudbuild/hello-cloudbuild'
  logging: 'NONE'
