steps:
  # - name: 'gcr.io/cloud-builders/docker'
  #   id: Build
  #   args:
  #   - 'build'
  #   - '-t'
  #   - 'gcr.io/joes-project-379413/hello-cloudbuild'
  #   - '.'
  # - name: 'gcr.io/cloud-builders/docker'
  #   id: Push
  #   args:
  #   - 'push'
  #   - 'gcr.io/joes-project-379413/hello-cloudbuild'
  - name: 'gcr.io/joes-project-379413/hello-cloudbuild@sha256:e29a366f0adbfd2328bc0f509812c491899f2bc08f4b329cc38b1c011fc89949'
    #entrypoint: 'bash'
    dir: '.'
    args:
     - '-c'
     - |
       pwd
       ls
       # echo "$_TEST"
       # echo "$PROJECT_ID"
options:
  logging: CLOUD_LOGGING_ONLY
  
