steps:
  # - name: 'gcr.io/cloud-builders/docker'
  #   id: Build
  #   args:
  #   - 'build'
  #   - '-t'
  #   - 'gcr.io/joes-project-379413/hello-cloudbuild'
  #   - '.'
  # - name: 'gcr.io/cloud-builders/docker'
  #   id: Push
  #   args:
  #   - 'push'
  #   - 'gcr.io/joes-project-379413/hello-cloudbuild'
  - name: 'gcr.io/cloud-builders/kubectl'
    entrypoint: 'bash'
    dir: '.'
    args:
     - '-c'
     - |
       pwd
       ls
       echo "$_MYVR"
       #python3 myf.py
       # echo "$_TEST"
       # echo "$PROJECT_ID"
options:
  logging: CLOUD_LOGGING_ONLY
  
